/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.ejerciciotareas.vista;

/**
 *
 * @author User
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenubarInicio = new javax.swing.JMenu();
        MenuItemAgregar = new javax.swing.JMenuItem();
        MenuItemPendientes = new javax.swing.JMenuItem();
        MenuItemCompletadas = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Sistema Básico de Gestión de Tareas");

        MenubarInicio.setText("Menú");

        MenuItemAgregar.setText("Agregar Tarea");
        MenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAgregarActionPerformed(evt);
            }
        });
        MenubarInicio.add(MenuItemAgregar);

        MenuItemPendientes.setText("Listar Tareas Pendientes ");
        MenuItemPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPendientesActionPerformed(evt);
            }
        });
        MenubarInicio.add(MenuItemPendientes);

        MenuItemCompletadas.setText("Listar Tareas Completadas");
        MenuItemCompletadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCompletadasActionPerformed(evt);
            }
        });
        MenubarInicio.add(MenuItemCompletadas);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        MenubarInicio.add(MenuItemSalir);

        jMenuBar1.add(MenubarInicio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAgregarActionPerformed

        this.setVisible(false);
        AgregarTarea ObjAgregarTarea = new AgregarTarea();
        ObjAgregarTarea.setVisible(true);

    }//GEN-LAST:event_MenuItemAgregarActionPerformed

    private void MenuItemCompletadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCompletadasActionPerformed

        this.setVisible(false);
        ListarTareasCompletadas objCompletas = new ListarTareasCompletadas();
        objCompletas.setVisible(true);

    }//GEN-LAST:event_MenuItemCompletadasActionPerformed

    private void MenuItemPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPendientesActionPerformed

        this.setVisible(false);
        ListarTareasPendientes objPendientes = new ListarTareasPendientes();
        objPendientes.setVisible(true);

    }//GEN-LAST:event_MenuItemPendientesActionPerformed

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        
        System.exit(WIDTH);
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemAgregar;
    private javax.swing.JMenuItem MenuItemCompletadas;
    private javax.swing.JMenuItem MenuItemPendientes;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenu MenubarInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
